services:
  api_gateway:
    build: ./http-api-gateway
    ports:
      - "3000:3000"
    volumes:
      - ./http-api-gateway/src:/usr/src/app/src
    command: npm run start:dev
    environment:
      - PORT=3000
  users_microservice:
    build: ./users-microservice
    volumes:
      - ./users-microservice/src:/usr/src/app/src
    command: npm run start:dev
  payments_microservice:
    build: ./payments-microservice
    volumes:
      - ./payments-microservice/src:/usr/src/app/src
    command: npm run start:dev
  nats:
    image: nats
    ports:
      - 4222:4222
  postgres_db:
    image: postgres:latest
    ports:
      - "5433:5432"
    environment:
      - POSTGRES_DB=nestjs_db
      - POSTGRES_USER=testuser
      - POSTGRES_PASSWORD=testuser123
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: